language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install: "pip install ."
# command to run tests
script:
  - "PYTHONPATH=. python tests/client_test.py"
  - "PYTHONPATH=. python3 tests/client_test.py"